lib/rankmode_web/router.ex
defmodule RankmodeWeb.Router do
  use RankmodeWeb, :router

  import RankmodeWeb.UserAuth
  import Plug.BasicAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {RankmodeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_admin do
    plug :accepts, ["json"]
    plug :basic_auth, Application.compile_env(:rankmode, :basic_auth)
  end

  scope "/", RankmodeWeb do
    pipe_through :browser
    get "/", Plug.Redirect, to: "/profiles"
  end

  # Other scopes may use custom stacks.
  # scope "/api", RankmodeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: RankmodeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", RankmodeWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]
    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", RankmodeWeb do
    pipe_through [:browser, :require_authenticated_user]
    live "/profiles", Live.Profiles.Index, :index
    live "/profiles/new", Live.Profiles.New, :new
    live "/profiles/edit/:profile", Live.Profiles.Edit, :edit
    live "/profiles/:profile/gameplays", Live.Gameplays.Index, :index
    live "/profiles/:profile/gameplays/new", Live.Gameplays.New, :new

    live "/cards", Live.Cards.Index, :index
    live "/cards/activate", Live.Cards.Activate, :activate
    live "/cards/edit/:card", Live.Cards.Edit, :edit

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", RankmodeWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  scope "/api", RankmodeWeb do
    pipe_through [:api]
    post "/gameplays", GameplayController, :create
    get "/gameplays/:gameplay", GameplayController, :show
  end

  scope "/api", RankmodeWeb do
    pipe_through [:api_admin]
    post "/cards", CardController, :create
    get "/cards/:card", CardController, :show
  end

end

lib/rankmode_web/live/cards/activate.ex
defmodule RankmodeWeb.Live.Cards.Activate do
  use RankmodeWeb, :live_view

  import Ecto.Changeset, only: [get_field: 2]

  alias Rankmode.Cards
  alias Rankmode.Profiles

  alias RankmodeWeb.Live.Components.Alert

  @impl true
  def handle_event("on:form:change", values, socket) do
    uid = values["card"]["uid"]
    card = Cards.Queries.get(:notactivated, uid: uid)

    case card do
      nil -> {:noreply, put_flash(socket, :error, "Card not found.")}
      _ -> {:noreply, socket}
    end
  end

  def handle_event("on:form:submit", values, socket) do

    user = socket.assigns.page.user
    uid = values["card"]["uid"]
    profile = Profiles.Queries.get(id: values["card"]["profiles"], user: user.id)
    card = Cards.Queries.get(:notactivated, uid: uid)

    case card do
      nil -> {:noreply, put_flash(socket, :error, "Card not found.")}
      _ ->
        case Cards.Commands.activate(card.id, %{
          uid: card.uid,
          user_id: user.id,
          game_id: profile.game.id,
          mix_id: profile.mix.id
        }) do
          {:ok, card} -> case Profiles.Commands.update(profile.id, %{
            name: profile.name,
            avatar_id: profile.avatar_id,
            user_id: profile.user_id,
            game_id: profile.game_id,
            mix_id: profile.mix_id,
            card_id: card.id
          }) do
            {:ok, _} -> {:noreply,
              put_flash(socket |> redirect(to: Routes.cards_index_path(socket, :index)), :info, "Card #{card.uid} Activated.")
            }
            {:error, changeset} -> {:noreply, socket |> assign(:changeset, changeset)}
          end
          {:error, changeset} -> {:noreply, socket |> assign(:changeset, changeset)}
        end
    end
  end

  @impl true
  def mount(_params, session, socket) do
    user = Helpers.current_user(session)
    profiles = Profiles.Queries.for(user: user.id)

    {:ok, socket
      |> Helpers.init(session)
      |> assign(:page, %{
        title: "Activate",
        breadcrumb: Helpers.crumbs(socket, [:cards, :cards_activate]),
        user: user,
        context: :cards
      })
      |> assign(:profiles, profiles)
      |> assign(:changeset, Cards.Changesets.empty())
    }
  end
end

lib/rankmode_web/live/cards/edit.ex
defmodule RankmodeWeb.Live.Cards.Edit do
  use RankmodeWeb, :live_view

  alias Rankmode.Cards
  alias Rankmode.Profiles

  alias RankmodeWeb.Live.Components.Alert

  defp update_card(card, profile, socket) do
    case Profiles.Commands.update(profile.id, %{
      name: profile.name,
      avatar_id: profile.avatar_id,
      user_id: profile.user_id,
      game_id: profile.game_id,
      mix_id: profile.mix_id,
      card_id: card.id
    }) do
      {:ok, _} -> case Cards.Commands.update(card.id, %{
        uid: card.uid,
        mix_id: profile.mix_id,
        game_id: profile.game_id
      }) do
        {:ok, _} -> {:noreply,
          put_flash(socket |> redirect(to: Routes.cards_index_path(socket, :index)), :info, "Card #{card.uid} Assigned to Profile #{profile.name}.")
        }
        {:error, changeset} -> {:noreply, socket |> assign(:changeset, changeset)}
      end
      {:error, changeset} -> {:noreply, socket |> assign(:changeset, changeset)}
    end
  end

  @impl true
  def handle_event("on:form:change", _values, socket) do
    {:noreply, socket}
  end

  def handle_event("on:form:submit", values, socket) do

    user = socket.assigns.page.user
    card = socket.assigns.card

    profile = Profiles.Queries.get(id: values["card"]["profiles"], user: user.id)
    old_profile = Profiles.Queries.get(card: card.id, user: user.id) || profile

    case is_nil(profile) || is_nil(old_profile) do
      true -> {:noreply, put_flash(socket, :error, "Profile not found.")}
      false ->
        case Profiles.Commands.remove_card(old_profile.id, %{
          name: old_profile.name,
          avatar_id: old_profile.avatar_id,
          user_id: old_profile.user_id,
          game_id: old_profile.game_id,
          mix_id: old_profile.mix_id
        }) do
          {:ok, _} -> update_card(card, profile, socket)
          {:error, changeset} -> {:noreply, socket |> assign(:changeset, changeset)}
        end
    end
  end

  @impl true
  def mount(params, session, socket) do

    user = Helpers.current_user(session)
    card_id = Map.get(params, "card", 0)
    card = Cards.Queries.get(id: card_id, user: user.id)

    mount(card, user, params, session, socket)
  end

  def mount(nil, _user, _params, _session, socket) do
    {:ok, socket |> redirect(to: Routes.cards_index_path(socket, :index))}
  end

  def mount(card, user, _params, session, socket) do
    profiles = Profiles.Queries.for(user: user.id)
    {:ok, socket
      |> Helpers.init(session)
      |> assign(:page, %{
        title: "Edit",
        breadcrumb: Helpers.crumbs(socket, [:cards, :cards_edit]),
        user: user,
        context: :cards
      })
      |> assign(:card, card)
      |> assign(:profiles, profiles)
      |> assign(:changeset, Cards.Changesets.empty())
    }
  end
end

lib/rankmode_web/live/cards/index.ex
defmodule RankmodeWeb.Live.Cards.Index do
  use RankmodeWeb, :live_view

  alias RankmodeWeb.Live.Components.Alert
  alias RankmodeWeb.Live.Components.Chip

  alias Rankmode.Cards

  @impl true
  def mount(_params, session, socket) do
    user = Helpers.current_user(session)
    cards = Cards.Queries.for(user: user.id)

    {:ok, socket |>
      Helpers.init(session)
      |> assign(:page, %{
        title: "Cards",
        breadcrumb: Helpers.crumbs(socket, [:cards]),
        user: user,
        context: :cards
      })
      |> assign(:cards, cards)
    }
  end
end

lib/rankmode_web/live/components/alert.ex
defmodule RankmodeWeb.Live.Components.Alert do
  use Phoenix.Component

  alias __MODULE__

  def new(%{dismissable: true} = assigns) do
    ~H"""
    <Alert.new class={@class}>
      <%= render_slot Map.get(assigns, :inner_block, "") %>
        <button phx-click="lv:clear-flash"
              phx-value-key={@key}
              type="button"
              class="box-content absolute top-0 right-0 p-4 text-sm text-white bg-transparent border-0 rounded w-4 h-4 z-2"
        >
        <span aria-hidden="true" class="text-center cursor-pointer">&#10005;</span>
      </button>
    </Alert.new>
    """
  end

  def new(assigns) do
    ~H"""
    <div class={["relative w-full p-4 text-white rounded-lg", @class]}>
      <%= render_slot @inner_block %>
    </div>
    """
  end

  def pink(assigns) do
    ~H"""
    <Alert.new class="bg-fuchsia-500" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def slate(assigns) do
    ~H"""
    <Alert.new class="bg-slate-400" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def green(assigns) do
    ~H"""
    <Alert.new class="bg-lime-500" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def red(assigns) do
    ~H"""
    <Alert.new class="bg-red-500" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def yellow(assigns) do
    ~H"""
    <Alert.new class="bg-yellow-400" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def blue(assigns) do
    ~H"""
    <Alert.new class="bg-cyan-500" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def gray(assigns) do
    ~H"""
    <Alert.new class="bg-gray-100" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def dark(assigns) do
    ~H"""
    <Alert.new class="bg-slate-700" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end
end

defmodule RankmodeWeb.Live.Components.Alert.Gradient do
  use Phoenix.Component

  alias RankmodeWeb.Live.Components.Alert

  def pink(assigns) do
    ~H"""
    <Alert.new class="border border-solid bg-gradient-to-tl from-purple-700 to-pink-500 border-fuchsia-300" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def slate(assigns) do
    ~H"""
    <Alert.new class="border border-solid bg-gradient-to-tl from-slate-600 to-slate-300 border-slate-100" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def green(assigns) do
    ~H"""
    <Alert.new class="border border-solid bg-gradient-to-tl from-green-600 to-lime-400 border-lime-300" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def red(assigns) do
    ~H"""
    <Alert.new class="border border-solid bg-gradient-to-tl from-red-600 to-rose-400 border-red-300" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def yellow(assigns) do
    ~H"""
    <Alert.new class="border border-solid bg-gradient-to-tl from-red-500 to-yellow-400 border-orange-100" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def blue(assigns) do
    ~H"""
    <Alert.new class="border border-solid bg-gradient-to-tl from-blue-600 to-cyan-400 border-cyan-200" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def gray(assigns) do
    ~H"""
    <Alert.new class="border border-solid bg-gradient-to-tl from-gray-400 to-gray-100 border-slate-100" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end

  def dark(assigns) do
    ~H"""
    <Alert.new class="border border-solid bg-gradient-to-tl from-gray-900 to-slate-800 border-slate-100" key={Map.get(assigns, :key, :info)} dismissable={Map.get(assigns, :dismissable, true)}><%= Map.get(assigns, :text, false) || render_slot Map.get(assigns, :inner_block, "") %></Alert.new>
    """
  end
end

lib/rankmode_web/live/components/button.ex
defmodule RankmodeWeb.Live.Components.Button do
  use Phoenix.Component
  # alias __MODULE__

  def new(assigns) do
    ~H"""
    <button type="button" class="inline-block px-6 py-3 font-bold text-center text-white uppercase align-middle transition-all rounded-lg cursor-pointer bg-gradient-to-tl from-purple-700 to-pink-500 leading-pro text-xs ease-soft-in tracking-tight-soft shadow-soft-md bg-150 bg-x-25 hover:scale-102 active:opacity-85 hover:shadow-soft-xs"></button>
    """
  end
end

lib/rankmode_web/live/components/toggle.ex
defmodule RankmodeWeb.Components.Toggle do
  use Phoenix.Component

  def toggle(assigns) do
    ~H"""

    """
  end
end

lib/rankmode_web/live/gameplays/index.ex
defmodule RankmodeWeb.Live.Gameplays.Index do
  use RankmodeWeb, :live_view
  alias Rankmode.Profiles
  alias Rankmode.Gameplays
  alias RankmodeWeb.Live.Components.Avatar
  alias RankmodeWeb.Live.Components.Chip

  @impl true
  def mount(params, session, socket) do

    user = Helpers.current_user(session)
    profile_id = Map.get(params, "profile", 0)
    profile = Profiles.Queries.get(id: profile_id, user: user.id)

    mount(params, session, socket, user, profile)
  end

  # If the profile does not belongs to user, then redirect to home
  def mount(_params, _session, socket, _user, nil) do
    {:ok, socket |> redirect(to: "/")}
  end

  def mount(_params, session, socket, user, profile) do

    gameplays = Gameplays.Queries.for(profile: profile.id)

    {:ok,
      socket
      |> Helpers.init(session)
      |> assign(:page, %{
        title: "Gameplays",
        breadcrumb: Helpers.crumbs(socket, [:profiles, :profiles_gameplays]),
        user: user,
        context: :profiles
      })
      |> assign(:profile, profile)
      |> assign(:gameplays, gameplays)
    }
  end
end

lib/rankmode_web/live/profiles/index.ex
defmodule RankmodeWeb.Live.Profiles.Index do
  use RankmodeWeb, :live_view
  alias RankmodeWeb.Live.Components.Chip
  alias RankmodeWeb.Live.Components.Avatar
  alias Rankmode.Profiles

  def get_leaderboard(socket, profile) do
    get_in(socket.assigns, [:leaderboards, "#{profile.id}#{profile.mix_id}"])
  end

  @impl true
  def mount(_params, session, socket) do

    user = Helpers.current_user(session)
    profiles = Profiles.Queries.for(user: user.id)

    {:ok,
      socket
      |> Helpers.init(session)
      |> assign(:page, %{
        title: "Profiles",
        breadcrumb: Helpers.crumbs(socket, [:profiles]),
        user: user,
        context: :profiles
      })
      |> assign(:profiles, profiles)
    }
  end
end

lib/rankmode_web/live/profiles/index.html.heex
<div class="m-0 font-sans antialiased font-normal text-base leading-default bg-gray-50 text-slate-500">

    <%= render RankmodeWeb.DashboardView, "sidebar.html", socket: @socket, page: @page %>

    <main class="ease-soft-in-out xl:ml-68.5 relative h-full max-h-screen rounded-xl transition-all duration-200">

      <%= render RankmodeWeb.DashboardView, "navbar.html", socket: @socket, page: @page %>

      <div class="w-full px-6 py-6 mx-auto">

        <div class="flex flex-wrap -mx-3">
          <div class="flex-none w-full max-w-full px-3">
            <div class="relative flex flex-col min-w-0 mb-6 break-words bg-white border-0 border-transparent border-solid shadow-soft-xl rounded-2xl bg-clip-border">
              <div class="p-6 pb-0 mb-0 bg-white border-b-0 border-b-solid rounded-t-2xl border-b-transparent">

                <div class="flex flex-row justify-between">
                  <div class="w-full grow">
                    <h6>Profiles</h6>
                  </div>

                  <div class="flex-none">
                    <a href={Routes.profiles_new_path(@socket, :new)} class="inline-block px-6 py-3 mr-3 font-bold text-center uppercase align-middle transition-all bg-transparent border rounded-lg cursor-pointer border-fuchsia-500 leading-pro text-xs ease-soft-in tracking-tight-soft shadow-soft-md bg-150 bg-x-25 hover:scale-102 active:opacity-85 hover:shadow-soft-xs text-fuchsia-500">
                    New Profile
                    </a>
                  </div>
                </div>

              </div>
              <div class="flex-auto px-0 pt-0 pb-2">
                <div class="p-0 overflow-x-auto">
                  <%= if @profiles == [] do %>
                    <div class="px-6 py-3 text-slate-500">
                      <p>
                        No profiles found.
                      </p>
                    </div>
                  <% else %>
                    <table class="items-center w-full mb-0 align-top border-gray-200 text-slate-500">
                      <thead class="align-bottom">
                        <tr>
                          <th class="px-6 py-3 font-bold text-left uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">Name</th>
                          <th class="px-6 py-3 pl-2 font-bold text-left uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">Level</th>
                          <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">PP/EXP</th>
                          <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">Created At</th>
                          <th class="px-6 py-3 font-semibold capitalize align-middle bg-transparent border-b border-gray-200 border-solid shadow-none tracking-none whitespace-nowrap text-slate-400 opacity-70"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <%= for profile <- @profiles do %>
                        <tr>
                          <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                            <div class="flex px-2 py-1">
                              <div>
                                <Avatar.new src={Routes.static_path(@socket, profile.avatar.image)}} round size="l" />
                              </div>
                              <div class="flex flex-col justify-center">
                                <h6 class="mb-0 leading-normal text-sm"><a href={Routes.gameplays_index_path(@socket, :index, profile.id)}><%= profile.name %></a></h6>
                                <p class="mb-0 leading-tight text-xs text-slate-400"><%= profile.mix.name %></p>
                              </div>
                            </div>
                          </td>
                          <td class="p-2 align-left bg-transparent border-b whitespace-nowrap shadow-transparent">
                            <Chip.green text={"LVL: #{profile.leaderboard.level}"} />
                          </td>
                          <td class="p-2 leading-normal text-center align-middle bg-transparent border-b text-sm whitespace-nowrap shadow-transparent">
                            <Chip.pink text={"PP: #{profile.leaderboard.pp}"} /> / <Chip.blue text={"EXP: #{profile.leaderboard.exp}"} />
                          </td>
                          <td class="p-2 text-center align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                            <span class="font-semibold leading-tight text-xs text-slate-400">
                              <Chip.slate text={Date.to_string(profile.inserted_at)} />
                            </span>
                          </td>
                          <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                            <a href={Routes.profiles_edit_path(@socket, :edit, profile.id)} class="inline-block px-6 py-3 mr-3 font-bold text-center text-white uppercase align-middle transition-all rounded-lg cursor-pointer bg-cyan-500 leading-pro text-xs ease-soft-in tracking-tight-soft shadow-soft-md bg-150 bg-x-25 hover:scale-102 active:opacity-85 hover:shadow-soft-xs">
                            Edit
                            </a>

                            <a href={Routes.gameplays_index_path(@socket, :index, profile.id)} class="inline-block px-6 py-3 mr-3 font-bold text-center text-white uppercase align-middle transition-all rounded-lg cursor-pointer bg-green-500 leading-pro text-xs ease-soft-in tracking-tight-soft shadow-soft-md bg-150 bg-x-25 hover:scale-102 active:opacity-85 hover:shadow-soft-xs">
                            Gameplays
                            </a>
                          </td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <%= render RankmodeWeb.DashboardView, "footer.html", socket: @socket %>
      </div>
    </main>
</div>